### ISSUE TITLE
Ulauncher doesn't respond until the program launched with ff/fd/fdir is closed

### ISSUE THREAD

**Issue by dhrunia** [brpaz/ulauncher-file-search#8] opened 2019-01-15 18:06 UTC
After opening a file/program from the search results, Ulauncher is not responding until the launched program is closed.

Steps to reproduce:
1. Launch Ulauncher
2. Search for a file
3. Open the file
4. Launch Ulauncher again

Step 4 won't launch Ulauncher unless the file opened in step3 is closed.

**Comment by brpaz** [comment] 2019-08-11 09:20
Cant reproduce it. I will close this. Feel free to reopen this issue if the problem still persists.

Thank you.

**Closed as completed by brpaz** 2019-08-11 09:20 UTC
Labels: bug
